# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_det_cpp <- function(X) {
    .Call(`_bare_eigen_det_cpp`, X)
}

set_eigen_num_threads_cpp <- function(n_cores) {
    invisible(.Call(`_bare_set_eigen_num_threads_cpp`, n_cores))
}

